// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byhpptibkfffcvlhlsjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5aHBwdGlia2ZmZmN2bGhsc2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTU3NjMsImV4cCI6MjA2NzQzMTc2M30.-uWlWC8Mxg78bsrA07s6yRzjqvhuzNOlHXAvUxmK0HI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});